export enum BlendMode {
  ADD,
  AVERAGE,
  COLOR_BURN,
  COLOR_DODGE,
  DARKEN,
  DIFFERENCE,
  EXCLUSION,
  GLOW,
  HARD_LIGHT,
  HARD_MIX,
  LIGHTEN,
  LINEAR_BURN,
  LINEAR_DODGE,
  LINEAR_LIGHT,
  MULTIPLY,
  NEGATION,
  NORMAL,
  OVERLAY,
  PHOENIX,
  PIN_LIGHT,
  REFLECT,
  SCREEN,
  SOFT_LIGHT,
  SUBTRACT,
  VIVID_LIGHT,
}

export const blendModes: Record<BlendMode, { mode: BlendMode; name: string }> = {
  [BlendMode.ADD]: { mode: BlendMode.ADD, name: 'Add' },
  [BlendMode.AVERAGE]: { mode: BlendMode.AVERAGE, name: 'Average' },
  [BlendMode.COLOR_BURN]: { mode: BlendMode.COLOR_BURN, name: 'Color Burn' },
  [BlendMode.COLOR_DODGE]: { mode: BlendMode.COLOR_DODGE, name: 'Color Dodge' },
  [BlendMode.DARKEN]: { mode: BlendMode.DARKEN, name: 'Darken' },
  [BlendMode.DIFFERENCE]: { mode: BlendMode.DIFFERENCE, name: 'Difference' },
  [BlendMode.EXCLUSION]: { mode: BlendMode.EXCLUSION, name: 'Exclusion' },
  [BlendMode.GLOW]: { mode: BlendMode.GLOW, name: 'Glow' },
  [BlendMode.HARD_LIGHT]: { mode: BlendMode.HARD_LIGHT, name: 'Hard Light' },
  [BlendMode.HARD_MIX]: { mode: BlendMode.HARD_MIX, name: 'Hard Mix' },
  [BlendMode.LIGHTEN]: { mode: BlendMode.LIGHTEN, name: 'Lighten' },
  [BlendMode.LINEAR_BURN]: { mode: BlendMode.LINEAR_BURN, name: 'Linear Burn' },
  [BlendMode.LINEAR_DODGE]: { mode: BlendMode.LINEAR_DODGE, name: 'Linear Dodge' },
  [BlendMode.LINEAR_LIGHT]: { mode: BlendMode.LINEAR_LIGHT, name: 'Linear Light' },
  [BlendMode.MULTIPLY]: { mode: BlendMode.MULTIPLY, name: 'Multiply' },
  [BlendMode.NEGATION]: { mode: BlendMode.NEGATION, name: 'Negation' },
  [BlendMode.NORMAL]: { mode: BlendMode.NORMAL, name: 'Normal' },
  [BlendMode.OVERLAY]: { mode: BlendMode.OVERLAY, name: 'Overlay' },
  [BlendMode.PHOENIX]: { mode: BlendMode.PHOENIX, name: 'Phoenix' },
  [BlendMode.PIN_LIGHT]: { mode: BlendMode.PIN_LIGHT, name: 'Pin Light' },
  [BlendMode.REFLECT]: { mode: BlendMode.REFLECT, name: 'Reflect' },
  [BlendMode.SCREEN]: { mode: BlendMode.SCREEN, name: 'Screen' },
  [BlendMode.SOFT_LIGHT]: { mode: BlendMode.SOFT_LIGHT, name: 'Soft Light' },
  [BlendMode.SUBTRACT]: { mode: BlendMode.SUBTRACT, name: 'Subtract' },
  [BlendMode.VIVID_LIGHT]: { mode: BlendMode.VIVID_LIGHT, name: 'Vivid Light' },
};

export const blendModesByName = Object.values(blendModes).reduce((acc, obj) => {
  acc[obj.name] = obj;
  return acc;
}, {} as Record<string, { mode: BlendMode; name: string }>);
